### ISSUE TITLE
Homepage with no featured item leaves everything far down the page

### ISSUE THREAD

**Issue by patrickmj** [omeka/theme-bigpicture#10]
If I don't have a featured item, no content appears until far down the page, essentially making the homepage look blank unless I scroll down.

Same result if I uncheck 'Show Featured Item' from theme configuration

**Comment by kimisgold** [comment]
This should now be fixed in 0eee6be. @patrickmj, could you pull and confirm?

**Comment by patrickmj** [comment]
Looks solid to me.
