### ISSUE TITLE
Latest update throwing errors

### ISSUE THREAD

**Issue by mebrett** [omeka/theme-bigpicture#13]
Pulled to latest commit this morning and the home page of my sites are throwing two errors.

On mebrett/Omeka and mebrett/demo, the error is:  
`Warning: array_keys() expects parameter 1 to be array, boolean given in /websites/omekadev/home/www/mebrett/demo/application/libraries/Omeka/Db/Table.php on line 133 Warning: in_array() expects parameter 2 to be array, null given in /websites/omekadev/home/www/mebrett/demo/application/libraries/Omeka/Db/Table.php on line 389 Warning: array_keys() expects parameter 1 to be array, boolean given in /websites/omekadev/home/www/mebrett/demo/application/libraries/Omeka/Db/Table.php on line 133 Warning: Invalid argument supplied for foreach() in /websites/omekadev/home/www/mebrett/demo/application/libraries/Omeka/Db/Table.php on line 366 Fatal error: Class 'EXHIBIT' not found in /websites/omekadev/home/www/mebrett/demo/application/libraries/Omeka/Db/Table.php on line 682`

It is the only thing that shows up on the page *but* the other pages on the site work perfectly fine.

Oddly, on mebrett/OmekaTwo I'm getting 
`Warning: array_keys() expects parameter 1 to be array, boolean given in /websites/omekadev/home/www/mebrett/OmekaTwo/application/libraries/Omeka/Db/Table.php on line 133 Warning: in_array() expects parameter 2 to be array, null given in /websites/omekadev/home/www/mebrett/OmekaTwo/application/libraries/Omeka/Db/Table.php on line 389 Warning: array_keys() expects parameter 1 to be array, boolean given in /websites/omekadev/home/www/mebrett/OmekaTwo/application/libraries/Omeka/Db/Table.php on line 133 Warning: Invalid argument supplied for foreach() in /websites/omekadev/home/www/mebrett/OmekaTwo/application/libraries/Omeka/Db/Table.php on line 366`

**Comment by kimisgold** [comment]
Pull and see if the problem is still happening?

**Comment by mebrett** [comment]
On http://dev.omeka.org/mebrett/demo/ I'm now getting a 404 error for the home page.

On mebrett/Omeka (which has a ridiculous number of plugins): 
```
exception 'Zend_View_Exception' with message 'script 'Items/featured.php' not found in path (/websites/omekadev/home/www/mebrett/Omeka/themes/bigpicture/:/websites/omekadev/home/www/mebrett/Omeka/application/views/scripts/:/websites/omekadev/home/www/mebrett/Omeka/plugins/ExhibitBuilder/views/public/:/websites/omekadev/home/www/mebrett/Omeka/plugins/ExhibitBuilder/views/shared/:/websites/omekadev/home/www/mebrett/Omeka/plugins/Geolocation/views/public/:/websites/omekadev/home/www/mebrett/Omeka/plugins/Geolocation/views/shared/:/websites/omekadev/home/www/mebrett/Omeka/plugins/SimplePages/views/public/)' in /websites/omekadev/home/www/mebrett/Omeka/application/libraries/Zend/View/Abstract.php:988
Stack trace:
#0 /websites/omekadev/home/www/mebrett/Omeka/application/libraries/Zend/View/Abstract.php(884): Zend_View_Abstract->_script('Items/featured....')
#1 /websites/omekadev/home/www/mebrett/Omeka/application/libraries/Zend/View/Helper/Partial.php(109): Zend_View_Abstract->render('Items/featured....')
#2 [internal function]: Zend_View_Helper_Partial->partial('Items/featured....', Array)
#3 /websites/omekadev/home/www/mebrett/Omeka/application/libraries/Zend/View/Abstract.php(350): call_user_func_array(Array, Array)
#4 /websites/omekadev/home/www/mebrett/Omeka/themes/bigpicture/functions.php(18): Zend_View_Abstract->__call('partial', Array)
#5 /websites/omekadev/home/www/mebrett/Omeka/themes/bigpicture/functions.php(18): Omeka_View->partial('Items/featured....', Array)
#6 /websites/omekadev/home/www/mebrett/Omeka/themes/bigpicture/functions.php(28): bigpicture_random_featured('Item')
#7 /websites/omekadev/home/www/mebrett/Omeka/themes/bigpicture/index.php(2): bigpicture_featured_html()
#8 /websites/omekadev/home/www/mebrett/Omeka/application/libraries/Omeka/View.php(114): include('/websites/omeka...')
#9 /websites/omekadev/home/www/mebrett/Omeka/application/libraries/Zend/View/Abstract.php(888): Omeka_View->_run('/websites/omeka...')
#10 /websites/omekadev/home/www/mebrett/Omeka/application/libraries/Zend/Controller/Action/Helper/ViewRenderer.php(912): Zend_View_Abstract->render('index.php')
#11 /websites/omekadev/home/www/mebrett/Omeka/application/controllers/IndexController.php(16): Zend_Controller_Action_Helper_ViewRenderer->renderScript('index.php')
#12 /websites/omekadev/home/www/mebrett/Omeka/application/libraries/Zend/Controller/Action.php(516): IndexController->indexAction()
#13 /websites/omekadev/home/www/mebrett/Omeka/application/libraries/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('indexAction')
#14 /websites/omekadev/home/www/mebrett/Omeka/application/libraries/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#15 /websites/omekadev/home/www/mebrett/Omeka/application/libraries/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#16 /websites/omekadev/home/www/mebrett/Omeka/application/libraries/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#17 /websites/omekadev/home/www/mebrett/Omeka/application/libraries/Omeka/Application.php(73): Zend_Application->run()
#18 /websites/omekadev/home/www/mebrett/Omeka/index.php(23): Omeka_Application->run()
#19 {main}
```
