### ISSUE TITLE
Advanced search .remove_search button not working in Firefox

### ISSUE THREAD

**Issue by adehner** [omeka/theme-bigpicture#19]
Clicking button.remove_search in the Advanced search form does not remove the button's parent (div.search-entry) in Mac Firefox. It works great in Chrome and Safari.

This appears to be theme related because button.remove_search is working in other themes.

button.remove_search is circled in the screenshot below:
<img width="659" alt="screen shot 2018-07-18 at 1 50 51 pm" src="https://user-images.githubusercontent.com/6174191/42907254-1731ca36-8a92-11e8-8c10-c05ce8fcaa0a.png">

**Comment by kimisgold** [comment]
Hi, I'm sorry I missed when this issue was initially reported. Were you ever able to resolve this behavior? I'm having trouble replicating it in Firefox 69.0.3.
