### ISSUE TITLE
Test new lightgallery viewer

### ISSUE THREAD

**Issue by kimisgold** [omeka/theme-bigpicture#20]
We had a [recent complaint about the limited zoom functionality in Chocolat](https://forum.omeka.org/t/lightbox-for-bigpicture-theme/9721) while also realizing that [themes with lightboxes need to respect the link to file metadata option](https://github.com/omeka/theme-centerrow/issues/14). [Lightgallery + lightslider](http://sachinchoolur.github.io/lightslider/examples.html) are a more robust solution that meets the above requirements.

On the `lightgallery` branch, we need to test the following: 
* Items with image media display in a slider that can open into a lightbox
* The image media display works for both desktop and mobile sizes
* In the lightbox, the user can access multiple levels of zoom
* The lightbox mode provides a link to the original file or to the file metadata if the site appearance option is selected

**Comment by mebrett** [comment]
Image files are displaying nicely.
Oddly, on item/show pages, the admin bar links to the Admin and Logout are no longer clickable.

**Comment by mebrett** [comment]
When I click configure for the theme, I get the following error

```
Zend_Form_Exception: No valid elements specified for display group in /var/www/html/mebrett/Omeka/application/libraries/Zend/Form.php:1843
Stack trace:
#0 /var/www/html/mebrett/Omeka/application/libraries/Zend/Form.php(1951): Zend_Form->addDisplayGroup(Array, 'item_show', Array)
#1 /var/www/html/mebrett/Omeka/application/libraries/Zend/Form.php(1987): Zend_Form->addDisplayGroups(Array)
#2 /var/www/html/mebrett/Omeka/application/libraries/Zend/Form.php(379): Zend_Form->setDisplayGroups(Array)
#3 /var/www/html/mebrett/Omeka/application/libraries/Zend/Form.php(404): Zend_Form->setOptions(Array)
#4 /var/www/html/mebrett/Omeka/application/forms/ThemeConfiguration.php(58): Zend_Form->setConfig(Object(Zend_Config))
#5 /var/www/html/mebrett/Omeka/application/libraries/Zend/Form.php(239): Omeka_Form_ThemeConfiguration->init()
#6 /var/www/html/mebrett/Omeka/application/controllers/ThemesController.php(77): Zend_Form->__construct(Array)
#7 /var/www/html/mebrett/Omeka/application/libraries/Zend/Controller/Action.php(516): ThemesController->configAction()
#8 /var/www/html/mebrett/Omeka/application/libraries/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('configAction')
#9 /var/www/html/mebrett/Omeka/application/libraries/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#10 /var/www/html/mebrett/Omeka/application/libraries/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#11 /var/www/html/mebrett/Omeka/application/libraries/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#12 /var/www/html/mebrett/Omeka/application/libraries/Omeka/Application.php(73): Zend_Application->run()
#13 /var/www/html/mebrett/Omeka/admin/index.php(28): Omeka_Application->run()
#14 {main}
```

**Comment by mebrett** [comment]
Lightgallery looks fine on module; I was able to use the zoom function in Chrome, Safari, and Firefox for iOS. 

I did notice that the file media display on the files/show page doesn't scale on mobile view, but I can make a separate issue for that if you'd like.

**Comment by kimisgold** [comment]
@mebrett 

> I did notice that the file media display on the files/show page doesn't scale on mobile view, but I can make a separate issue for that if you'd like.

Yup, I'd appreciate that!

**Comment by kimisgold** [comment]
@mebrett Latest changes should address all the above issues. It should be ready for another look.

**Comment by mebrett** [comment]
Everything looks good - files/show on mobile is fixed, I can configure the theme.
