### ISSUE TITLE
PDF Request

### ISSUE THREAD

**Issue by mvasquez222** [omeka/theme-bigpicture#21]
Hi,

I greatly apologize if this is not the right place for this request. I would really like to use the Big Picture theme for my Omeka site. I know the point is to focus on photographs, but is there anything I can adjust or add that can allow PDFs to also show up where the images do? I tried to fiddle around, I manged to get them to show up but they don't fit as nicely. 

I realize it's the opposite of what the themes intended purpose is, if it's too difficult to do, please ignore my request!

Thank you.

**Comment by kimisgold** [comment]
At the moment, there isn't an easy way to support PDFs in the current image viewer, but I'd be happy to look into this feature. While I'm doing so, could you somehow share the work you've done so far?

**Comment by mvasquez222** [comment]
Thank you for your quick reply! I'll attach the php file I was playing with. I get the PDF to come up, but it's killing the page layout. I was every so slowly adjusting it, but it's still not lining up nice. 

https://github.com/omeka/theme-bigpicture/files/3794768/show.txt

Here's an example of what it ends up looking like: http://capturingcreteorg.ipage.com/omeka/items/show/245

I was just hoping to get the PDF to hang out on the right and the data to chill on the left side. I didn't want to mess around with anything too much. I don't need it in any fancy viewer, the PDF viewer plugin works fine (which is what I'm using).

**Comment by kimisgold** [comment]
The tricky part for me is supporting PDF display for generic use. Here are a couple of use cases I need to consider:

1. If the user attaches multiple PDFs to an item, what would be the ideal way to display them?
2. How should the theme handle file display if a user attaches a mix of PDF and images to an item?

**Comment by mvasquez222** [comment]
I completely understand where you're coming from! Thank you for taking this into consideration.

**Comment by kimisgold** [comment]
PDF support now included v1.6.
