### ISSUE TITLE
Test that non-image files respect to "link to file metadata" setting

### ISSUE THREAD

**Issue by kimisgold** [omeka/theme-bigpicture#22]
Big Picture groups files that can't display in the image viewer in a "Files" section in the metadata. On the master branch, test that these file links go to either the metadata view or the original file based off the "link to file metadata" appearance setting.

**Comment by mebrett** [comment]
Is behaving like TheDaily and consistently goes from the file link on the item/show page to the file/show page, regardless of appearance settings.

**Comment by kimisgold** [comment]
The fix should be up—could you pull and check?

**Comment by mebrett** [comment]
It now works as expected.
