### ISSUE TITLE
Broken Home Page

### ISSUE THREAD

**Issue by djbroccoli** [omeka/theme-bigpicture#23]
Hi there,

I just noticed that the homepage for my website is not displaying the featured items/exhibits as I would expect it to and also there seems to be something up with the menu display (#top-nav) I can confirm the issues are present on both Firefox and Safari. I might add that it is also working great on mobile. For reference the website is http://www.undergroundarchiveproject.org. Let me know if this is something that might be beyond the scope of the theme code, but I just wanted to post in case others are experiencing similar issues. 

Best,
Brock

**Comment by kimisgold** [comment]
Hi @djbroccoli, I only just now saw this issue—did you close this because the top nav issue was resolved? If it wasn't, can you clarify the display issue that you're seeing?
