### ISSUE TITLE
How to remove "Browse Exhibits" from the bottom of every page

### ISSUE THREAD

**Issue by ecbettinger** [omeka/theme-bigpicture#25]
Hello!

I'm not sure if my issue is an Omeka issue or a theme issue, but I have combed over the Omeka documentation and can't find anything there, so I thought I would try here. In advance, thanks so much for taking a look! 

Right now, at the bottom of every page in my exhibit, is a link that says "Browse Exhibits," and and an image representing an exhibit. But I want to remove this link and photo. I only have one exhibit on the site, so each page is pretty short, so the link and photo on the bottom creates a confusing user experience. 

How can I remove this? I tried temporarily deleting the footer php file for both the site and the theme, and this aspect of the bottom of the page was unchanged. 

Thank you so much!

**Comment by zerocrates** [comment]
This is just the bottom of every _exhibit_ page, right?

This is a Big Picture exclusive thing, I think, but it's not in the footer, it's in the Exhibit Builder "show" page, at exhibit-builder/exhibits/show.php within the theme.

**Comment by ecbettinger** [comment]
Yes, it worked!

Thanks very much.
