### ISSUE TITLE
Video embed

### ISSUE THREAD

**Issue by jcmundy** [omeka/theme-bigpicture#26]
We are using BigPicture on a site, and realized that we have a few items that we want to embed videos on rather than focus on an image.  Do you have a recommended way to handle this?  Thank you.

**Comment by kimisgold** [comment]
I'm interested in adding more video support, and use case details would be helpful.

* What video format are you using?
* How are you bringing these videos into Omeka?
* Do you plan on attaching video alongside images to a single item?

**Comment by jcmundy** [comment]
I was planning to iframe videos from both youtube and vimeo (depending on the video) to reduce load on the server, though I could upload most of the videos in a standard format if necessary.  

If the videos could create a thumbnail image for the browse view, I wouldn't need to upload images, but I would create an image (for the browse view) alongside the video if it wouldn't have a thumbnail.  

Thank you for your help!

**Comment by kimisgold** [comment]
Omeka Classic doesn't currently have a way to attach iframe-based video embeds as files, so you'd have to upload video as files. If you have ImageMagick and ffmpeg installed on your server, they should generate a thumbnail properly.

I'm currently drafting video support. If you're willing to wait a few days and to help test this, I'll let you know when it's ready.

**Comment by jcmundy** [comment]
Thank you.  I'd be happy to help test it.

**Comment by kimisgold** [comment]
@jcmundy I've pushed an update with video support. If you're comfortable with git, you can simply pull in the latest changes from this repo. Otherwise, download [this zip](https://github.com/omeka/theme-bigpicture/archive/refs/heads/master.zip) and copy its contents into your bigpicture theme folder.

**Comment by jcmundy** [comment]
Thank you!  This is actually working quite well for me. The icon shows up on the left and I can click it to watch the video. I was wondering if the videos (I'm testing a couple uploaded as items) can support captions?  I can get the srt/vtt files.

**Comment by zerocrates** [comment]
The [Html5Media](https://omeka.org/classic/plugins/Html5Media/) plugin supports srt/vtt as long as the subtitle file is uploaded to the same item and shares the same "base" filename as the video.

**Comment by jcmundy** [comment]
Thank you, I was able to test and to get the captions to work testing the same video in a different Omeka site, but not within this theme.  Our website is not being publicly shared yet, but I'm happy to send you a link over email to show you how it's looking.

**Comment by kimisgold** [comment]
@jcmundy The subtitles are ready to test. You need to meet these conditions:

* Subtitle and video files must all share the same base file name (ex: "video.mp4", "video.srt", "video.vrtt")
* The subtitle metadata must include the following:
  * Dublin Core: Type value must be "subtitles"
  * Dublin Core: Language value must be the language code
  * Dublin Core: Title value should be the label for your track
 * Multiple subtitle tracks are supported. They still must share the same base file name as the video: the user must differentiate between them using their Dublin Core metadata.

**Comment by jcmundy** [comment]
I've got the update in my site.  I see the subtitles button, and my label shows up for the video subtitles (same link that I emailed to you), but the subtitles themselves are not displaying for me.  Am I missing something?  Thank you!

**Comment by kimisgold** [comment]
It has to do with your subtitles file. Include the WEBVTT header, and make sure your timestamps don't include the commas.

My example correction of the top of your file:

```
WEBVTT

1
00:00:13.645 --> 00:00:14.494
Falcon, Houston.
```

**Comment by jcmundy** [comment]
Thank you so much!  It's working now.
