### ISSUE TITLE
Certain file types do not display on item show

### ISSUE THREAD

**Issue by mebrett** [omeka/theme-bigpicture#3]
mp4, pdf, and txt files do not load in the item/show page, although they do have thumbnails present on item browse. 

Also true of The Daily on Classic and [S](https://github.com/omeka-s-themes/centerrow/issues/11).

If this is just a feature of the file viewer, we'll need to make a note in the documentation somewhere.

#1

**Comment by kimisgold** [comment]
Non-image media should appear in the sidebar as "Other Media" links. I've restructured the item show a bit to better filter out these specific file types, though let me know if they still try to appear int he file gallery.

**Comment by mebrett** [comment]
Non media (specifically txt and pdf files are still trying to load in the file gallery, particularly if they're the only media for an item. 

I'm not seeing the Other Media header in the sidebar at all.

**Comment by kimisgold** [comment]
My imagemagick doesn't generate file derivatives for pdfs and txt files properly, and I was relying on presence of file derivatives to sort images from non-images. I'm looking at the MIME type for that check now, so hopefully that should be more reliable.

**Comment by kimisgold** [comment]
@mebrett Could you check to see if this is still occurring?

**Comment by mebrett** [comment]
Viewer is now only displaying images and the pdfs, mp4s, etc are showing up as "other media."
