### ISSUE TITLE
Test for fixed ARIA roles

### ISSUE THREAD

**Issue by kimisgold** [omeka/theme-bigpicture#32]
On the landing page, there were previously broken ARIA roles that have been addressed in https://github.com/omeka/theme-bigpicture/commit/b4de5f0b91cfd7e91a720d3033c66a6f0b48ba0b. Use accessibility tools to check that these errors have been resolved.

**Comment by katknow** [comment]
All of the accessibility checkers are flagging `.slick-track`, but everything else is fine.

**Comment by kimisgold** [comment]
It seems slick carousel gives its container a `role="listbox"` and that requires a title or other kind of labeling. I've just added it in https://github.com/omeka/theme-bigpicture/commit/d4c94670dc20d8722519577f6bccf4bc53eb3383.

**Comment by katknow** [comment]
All seems to be good now--no flags.
