### ISSUE TITLE
Lightgallery

### ISSUE THREAD

**Issue by lesleydemuynck** [omeka/theme-bigpicture#34]
Hello, I'm not a developer, but I just want to report a small bug (and the solution to it). 

I installed your theme, but encountered a problem when opening an image item. There was a Zend_Loader_PluginLoader_Exception
Plugin by name 'Lightgallery' was not found in the registry; used paths:
Omeka_View_Helper_: (url)

When I looked in the application folder on my web server I noticed that indeed the file called was named LightGallery.php, with a capital G. I changed it to a small g and everything worked again.

**Comment by kimisgold** [comment]
@lesleydemuynck Thank you for bringing this to our attention. We've updated the theme to use the global function `lightgallery()`, which should be a little cleaner to use. In doing so, that should fix the bug you encountered. [You can get the v1.6.4 here.](https://github.com/omeka/theme-bigpicture/releases/download/v1.6.4/bigpicture-1.6.4.zip)
