### ISSUE TITLE
Mobile view of Exhibit pages scrunched in nav

### ISSUE THREAD

**Issue by mebrett** [omeka/theme-bigpicture#4]
While testing #1  on mobile, there were two things I noticed:
1. The next/previous options for navigating within an exhibit end up overlapping content a bit if those pages have long names.
![longnames](https://cloud.githubusercontent.com/assets/2314070/22385806/3d270c98-e4a2-11e6-8ebe-aa49ff9cd79e.png)

2. On mobile (on both the iPhone and the Blu (Android)), the browse exhibits options at the bottom of each exhibit page get smushed into illegibility
![browseblocks](https://cloud.githubusercontent.com/assets/2314070/22385830/5d6ee886-e4a2-11e6-8c26-da77afb9a389.png)

**Comment by kimisgold** [comment]
I overlooked this particular view for mobile. There are some new styles for it if you pull.
