### ISSUE TITLE
Error on an exhibits page

### ISSUE THREAD

**Issue by patrickmj** [omeka/theme-bigpicture#7]
Sorry, not sure yet details of how to reproduce it, but I hit this

```
: Uncaught TypeError: Argument 1 passed to file_display_url() must be an instance of File, null given, called in /var/www/Omeka/themes/bigpicture/exhibit-builder/exhibits/browse.php on line 30 and defined in /var/www/Omeka/application/libraries/globals.php:3297 Stack trace: #0 /var/www/Omeka/themes/bigpicture/exhibit-builder/exhibits/browse.php(30): file_display_url(NULL, 'fullsize') #1 /var/www/Omeka/application/libraries/Omeka/View.php(117): include('/var/www/Omeka/...') #2 /var/www/Omeka/application/libraries/Zend/View/Abstract.php(888): Omeka_View->_run('/var/www/Omeka/...') #3 /var/www/Omeka/application/libraries/Zend/Controller/Action/Helper/ViewRenderer.php(912): Zend_View_Abstract->render() #4 /var/www/Omeka/application/libraries/Zend/Controller/Action/Helper/ViewRenderer.php(933): Zend_Controller_Action_Helper_ViewRenderer->renderScript('exhibits/browse...', NULL) #5 /var/www/Omeka/application/libraries/Zend/Controller/Action/Helper/ViewRenderer.php(972): Zend_Controller_Action_Helper_ViewRenderer->ren in 
```

Page is like `http://localhost/Omeka/exhibits`

**Comment by kimisgold** [comment]
@patrickmj Could you pull and see if this is still happening?

**Comment by patrickmj** [comment]
On current master, not seeing the message. But also not seeing the associated image. Item selected for associated image has two files.

**Comment by patrickmj** [comment]
No image with single-file item set for cover image. No image when I added same item to the first page.

**Comment by kimisgold** [comment]
@patrickmj Hopefully https://github.com/omeka/theme-bigpicture/commit/942ed1f508e00ae8fd7d613b5bd6286ee41ad03d should fix it.

**Comment by patrickmj** [comment]
Near-total happiness! 

Images are there, but one of my particular images leaves some room on the right where it looks like the background color seeps through



![bigpicture](https://cloud.githubusercontent.com/assets/153262/22845730/0a7b88c6-efb2-11e6-8759-77a9d24e60cf.png)

**Comment by patrickmj** [comment]
yep. that's what it looks like
