### ISSUE TITLE
File gallery not working in Safari

### ISSUE THREAD

**Issue by mebrett** [omeka/theme-bigpicture#9]
I've walked backwards and I think it's something in [commit ee869fa](https://github.com/omeka/theme-bigpicture/commit/ee869fa40cc1ecb8145597dd725a78fd2735b772). The commit before that, jpgs and things show up fine in the file viewer. 

With that commit and every subsequent one, the gallery either loads as a gray box (if the item has a single file) or loads a gray box with the file browser across top (if the item has more than one file)
![screen shot 2017-02-07 at 3 43 42 pm](https://cloud.githubusercontent.com/assets/2314070/22710676/467868ac-ed4c-11e6-8b80-9bf6b4736dd6.png)

**Comment by kimisgold** [comment]
Could I get confirmation that this was fixed in f9af0c4?

**Comment by mebrett** [comment]
Fixed
